# Generated by Django 6.1.1 on 2026-09-22 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('token', models.IntegerField(blank=True, null=True)),
                ('class_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='tag', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('color_code', models.CharField(default='#3b82f6', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('config_json', models.JSONField(default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('keywords_json', models.JSONField(default=list)),
                ('types_json', models.JSONField(blank=True, default=list)),
                ('exclusions_json', models.JSONField(blank=True, default=list)),
                ('weight', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(db_index=True, max_length=512)),
                ('base_class_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('interfaces_json', models.JSONField(blank=True, default=list)),
                ('is_value_type', models.BooleanField(default=False)),
                ('is_enum', models.BooleanField(default=False)),
                ('is_interface', models.BooleanField(default=False)),
                ('is_abstract', models.BooleanField(default=False)),
                ('type_token', models.IntegerField(blank=True, null=True)),
                ('importance_score', models.IntegerField(db_index=True, default=0)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('primary_category', models.CharField(db_index=True, default='GENERAL', max_length=50)),
                ('context_type', models.CharField(choices=[('STATE', 'State'), ('DATA', 'Data'), ('UI', 'UI'), ('VISUAL', 'Visual'), ('AUDIO', 'Audio'), ('ANIMATION', 'Animation'), ('NETWORK', 'Network')], default='STATE', max_length=20)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='analyzer.assembly')),
            ],
            options={
                'ordering': ['-importance_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnumDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('underlying_type', models.CharField(default='int', max_length=50)),
                ('items_json', models.JSONField(default=list)),
                ('class_def', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enum_info', to='analyzer.classdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type_name', models.CharField(db_index=True, max_length=255)),
                ('is_static', models.BooleanField(db_index=True, default=False)),
                ('is_const', models.BooleanField(default=False)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('offset_value', models.IntegerField(blank=True, db_index=True, null=True)),
                ('offset_hex', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('importance_score', models.IntegerField(db_index=True, default=0)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('primary_category', models.CharField(db_index=True, default='GENERAL', max_length=50)),
                ('context_type', models.CharField(choices=[('STATE', 'State'), ('DATA', 'Data'), ('UI', 'UI'), ('VISUAL', 'Visual'), ('AUDIO', 'Audio'), ('ANIMATION', 'Animation'), ('NETWORK', 'Network')], default='STATE', max_length=20)),
                ('class_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='analyzer.classdefinition')),
            ],
            options={
                'ordering': ['offset_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MethodDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('return_type', models.CharField(default='void', max_length=255)),
                ('signature', models.TextField(blank=True, default='')),
                ('is_static', models.BooleanField(default=False)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_abstract', models.BooleanField(default=False)),
                ('rva_value', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('rva_hex', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('va_value', models.BigIntegerField(blank=True, null=True)),
                ('va_hex', models.CharField(blank=True, default='', max_length=32)),
                ('file_offset_value', models.BigIntegerField(blank=True, null=True)),
                ('file_offset_hex', models.CharField(blank=True, default='', max_length=32)),
                ('method_token', models.IntegerField(blank=True, null=True)),
                ('importance_score', models.IntegerField(db_index=True, default=0)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('primary_category', models.CharField(db_index=True, default='GENERAL', max_length=50)),
                ('class_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='analyzer.classdefinition')),
            ],
            options={
                'ordering': ['-importance_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('method_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='analyzer.methoddefinition')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('platform', models.CharField(db_index=True, default='UNKNOWN', max_length=50)),
                ('architecture', models.CharField(db_index=True, default='UNKNOWN', max_length=50)),
                ('unity_version', models.CharField(default='UNKNOWN', max_length=100)),
                ('metadata_version', models.CharField(blank=True, max_length=50, null=True)),
                ('binary_name', models.CharField(default='libil2cpp.so', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('DETECTING', 'Detecting'), ('PARSING', 'Parsing'), ('INDEXING', 'Indexing'), ('ANALYZING', 'Analyzing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('classes_count', models.IntegerField(default=0)),
                ('methods_count', models.IntegerField(default=0)),
                ('fields_count', models.IntegerField(default=0)),
                ('properties_count', models.IntegerField(default=0)),
                ('enums_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'status'], name='analyzer_pr_name_f47e21_idx'), models.Index(fields=['platform', 'architecture'], name='analyzer_pr_platfor_e828ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='analyzer.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='analyzer.project'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='analyzer.project'),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('context_type', models.CharField(default='STATE', max_length=20)),
                ('score_reasons_json', models.JSONField(default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='analyzer.project')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('current_step', models.IntegerField(default=0)),
                ('step_description', models.CharField(default='Queued', max_length=255)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='analyzer.project')),
            ],
        ),
        migrations.CreateModel(
            name='AddressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(default='FIELD', max_length=50)),
                ('class_name', models.CharField(db_index=True, max_length=255)),
                ('member_name', models.CharField(db_index=True, max_length=255)),
                ('address_type', models.CharField(choices=[('FIELD_OFFSET', 'Field Offset'), ('METHOD_RVA', 'Method RVA'), ('VIRTUAL_ADDRESS', 'Virtual Address'), ('FILE_OFFSET', 'File Offset'), ('STATIC_ADDRESS', 'Static Address'), ('POINTER', 'Pointer'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=30)),
                ('value_hex', models.CharField(db_index=True, max_length=32)),
                ('value_int', models.BigIntegerField(db_index=True)),
                ('architecture', models.CharField(default='UNKNOWN', max_length=50)),
                ('source', models.CharField(default='Analysis', max_length=255)),
                ('derivation', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('verified', models.BooleanField(default=True)),
                ('field_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_records', to='analyzer.fielddefinition')),
                ('method_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_records', to='analyzer.methoddefinition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_records', to='analyzer.project')),
            ],
            options={
                'ordering': ['address_type', 'class_name', 'value_int'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('getter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('setter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='analyzer.classdefinition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_class', models.CharField(db_index=True, max_length=255)),
                ('target_class', models.CharField(db_index=True, max_length=255)),
                ('relation_type', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='analyzer.project')),
            ],
        ),
        migrations.CreateModel(
            name='WarningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('message', models.TextField()),
                ('target_object', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(default='WARNING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='analyzer.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['name', 'primary_category'], name='analyzer_fi_name_c26cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['offset_value', 'is_static'], name='analyzer_fi_offset__215082_idx'),
        ),
        migrations.AddIndex(
            model_name='methoddefinition',
            index=models.Index(fields=['name', 'primary_category'], name='analyzer_me_name_8f839e_idx'),
        ),
        migrations.AddIndex(
            model_name='methoddefinition',
            index=models.Index(fields=['rva_value'], name='analyzer_me_rva_val_685e4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='namespace',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='classdefinition',
            index=models.Index(fields=['project', 'name'], name='analyzer_cl_project_d4e85f_idx'),
        ),
        migrations.AddIndex(
            model_name='classdefinition',
            index=models.Index(fields=['project', 'primary_category'], name='analyzer_cl_project_a9d972_idx'),
        ),
        migrations.AddIndex(
            model_name='classdefinition',
            index=models.Index(fields=['project', 'importance_score'], name='analyzer_cl_project_124d59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assembly',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['project', 'category', 'score'], name='analyzer_an_project_ec3555_idx'),
        ),
        migrations.AddIndex(
            model_name='addressrecord',
            index=models.Index(fields=['project', 'address_type'], name='analyzer_ad_project_b5be3f_idx'),
        ),
        migrations.AddIndex(
            model_name='addressrecord',
            index=models.Index(fields=['class_name', 'member_name'], name='analyzer_ad_class_n_1364bb_idx'),
        ),
        migrations.AddIndex(
            model_name='addressrecord',
            index=models.Index(fields=['value_int', 'address_type'], name='analyzer_ad_value_i_b852d6_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['project', 'source_class', 'target_class'], name='analyzer_re_project_c4d805_idx'),
        ),
    ]
