# Generated by Django 6.1.1 on 2026-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='engine_type',
            field=models.CharField(default='Unity (IL2CPP)', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='is_apk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='package_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='target_sdk',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
